config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
 
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :reviews
  resources :guitars do 
    resources :reviews, only: [:new, :index]
  end 
  resources :makes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guitar.rb
class Guitar < ApplicationRecord
  belongs_to :make
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews
  accepts_nested_attributes_for :make

  validates :kind, presence: true
  validate :not_a_duplicate

  scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}

    def self.alpha
      order(:kind)
    end 


    def make_attributes=(attributes)
      make = Make.find_or_create_by(attributes) if !attributes['name'].empty?
    end

    def not_a_duplicate
      if Guitar.find_by(kind: kind, make_id: make_id)
      errors.add(:kind, "has already been added for that make")
    end 
  end

  def kind_and_make
    "#{kind} - #{make.name}"
  end 

end
 

app/models/make.rb
class Make < ApplicationRecord
    has_many :guitars
    validates :name, presence: true, uniqueness: true
    
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :guitar

  validates :title, presence: true
  validates :stars, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 6}

  validates :guitar, uniqueness: { scope: :user, message: "has already been reviewed by you" }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :reviewed_guitars, through: :reviews, source: :guitar

  has_many :guitars 

  validates :username, uniqueness: true,  presence: true
  

  has_secure_password

  def self.create_by_google_omniauth(auth)
    self.find_or_create_by(username: auth[:info][:email]) do |u|
      u.password = SecureRandom.hex
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private
  
    def logged_in?
      !!session[:user_id]
    end

    def current_user
    @current_user ||= User.find_by_id(session[:user_id])
    end 

    def redirect_if_not_logged_in
      redirect_to login_path if !logged_in?
    end

end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
     before_action :set_guitar, only:[:show, :edit, :update]

    def index
    @guitars = Guitar.order_by_rating.includes(:make)
    end 

    def new
        redirect_if_not_logged_in
    @guitar = Guitar.new
    @guitar.build_make
    end

    def create
        @guitar = Guitar.new(guitar_params)
        @guitar.user_id = session[:user_id]
        if @guitar.save
        redirect_to guitar_path(@guitar)
        else
            @guitar.build_make
            render :new
        end
    end 

    def show
    end

    def edit
    end

    def update
        if @guitar.update(guitar_params)
            redirect_to guitar_path(@guitar)
          else
            render :edit
          end
    end

    private

    def guitar_params
        params.require(:guitar).permit(:kind, :description, :make_id, make_attributes: [:name])
    end 

    def set_guitar
        @guitar = Guitar.find_by(params[:id])
        redirect_to guitars_path if !@guitar
    end

end

app/controllers/makes_controller.rb
class MakesController < ApplicationController

def index
    @makes = Make.all
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def new
    redirect_if_not_logged_in
    if @guitar = Guitar.find_by_id(params[:guitar_id])
        @review = @guitar.reviews.build
    else
        @review = Review.new
    end
end 

def create
    @review = current_user.reviews.build(review_params)
    if @review.save
    redirect_to review_path(@review)
    else
        render :new
    end
end

def show
    @review = Review.find_by_id(params[:id])
end 

def index
    if params[:guitar_id]
        @guitar = Guitar.find_by_id(params[:guitar_id])
        @reviews = @guitar.reviews 
    else
        
    @reviews =  Review.all
    end
end 

def review_params
    params.require(:review).permit(:guitar_id, :content, :stars, :title)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
    end 

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end 

    def new

    end 

    def create

        if params[:provider] == 'google_oauth2'
            @user = User.create_by_google_omniauth(auth)
            session[:user_id] = @user.id
            redirect_to user_path(@user)

        else 


        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
        else
            flash[:error] = "Sorry, Login info was incorrect. Please try again"
            redirect_to login_path
        end
      end 
    end

    def omniauth
        @user = User.create_by_google_omniauth(auth)

    session[:user_id] = @user.id
    redirect_to user_path(@user)
    end

    def auth
        request.env['omniauth.auth']
      end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end 

    def show
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end 

    def user_params
        params.require(:user).permit(:username, :password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

    def render_nav_bar
        if logged_in?
          render partial: 'layouts/loggedin_links'
        
        end
      end

end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def display_header(review)
        if params[:guitar_id]
            content_tag(:h1, "Add a Review for #{review.guitar.kind} -  #{review.guitar.make.name}")
        else
          content_tag(:h1, "Create a review")
        end
      end
    end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/guitars/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @guitar} %>

<%= form_for(@guitar) do |f| %>
    <div>
    <%= f.label :kind %>
    <%= f.text_field :kind %>
    </div>
    <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
    </div>

    <p> Select a Make that exists </p>
    <div> 
    <%= f.collection_select :make_id, Make.all, :id, :name, include_blank: 'Select One'%>

    </div>

    <p> Or create a new Make: </p>
    <div>
    <%= f.fields_for :make do |m| %>
        <%= m.label :name %>
        <%= m.text_field :name %>
        <% end %>
    </div>
        <br>
    <%= f.submit "Create a Guitar" %>
    <% end %>

app/views/guitars/edit.html.erb
<h1>Edit your Guitar</h1>



<%= render partial: 'form'%>

app/views/guitars/index.html.erb
<h1>All the Guitars</h1>

<% @guitars.each do |g| %> 

    <h2><%= g.kind %> - <%= g.make.name %> </h2>
    <%= link_to "Write a review", new_guitar_review_path(g.id) %>
    <div>
    <p><%= g.description %></p>
    </div>
    <% end %> 

app/views/guitars/new.html.erb
<h1>Make a new Guitar</h1>

<%= render partial: 'form'%>

app/views/guitars/show.html.erb
<h1><%= @guitar.kind%> </h1>

<h2><%= @guitar.kind%> - <%= @guitar.make.name %> </h2>
<div>
<p><%= @guitar.description %></p>

<h3>Added by: <%= @guitar.user.username %> </h3>

<%= link_to "Edit #{@guitar.kind} " " - " " #{@guitar.make.name}", edit_guitar_path(@guitar) if @guitar.user == current_user%>

</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Log Out", logout_path, method: :delete %> |
<%= link_to "Add an Guitar", new_guitar_path %> |
<%= link_to "All Guitars", guitars_path %> |
<%= link_to "Add a Review", new_review_path %> |
<%= link_to "All Reviews", reviews_path %> |
<%= link_to "All Makes", makes_path %> |

app/views/layouts/_loggedout_links.html.erb
<p>Welcome to Guitar Rating Site<p>

<p>
<%= link_to "Login", login_path %>
OR
<%= link_to "Signup", signup_path %>
OR
<%= button_to "Sign in with Google", "/auth/google_oauth2" %>
</p>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuitarRatingSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
  <div><%= render_nav_bar %></div>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/makes/index.html.erb
<h1>All the Makes</h1>

<ol>
  <% @makes.each do |make| %>
    <li><%= make.name%></li>
  <% end %>
</ol>

app/views/reviews/index.html.erb
<h1>All the Reviews</h1>

<ol>
<% @reviews.each do |r| %>
    <li><%= r.guitar.make.name%> - <%= r.guitar.kind%>: - <%= r.title%> - <%= r.stars%></li> <br>
<% end %>
</ol>

app/views/reviews/new.html.erb
<%=  display_header(@review)%>

<%= render partial: 'layouts/errors', locals: {object: @review}   %>

 

<%= form_for(@review) do |f| %>
    <% if params[:guitar_id] %>
        <%= f.hidden_field :guitar_id %>
        <% else %>
        <div>
            <%= f.label :guitar_id, "Select a Guitar" %>
            <%= f.collection_select :guitar_id, 
            Guitar.alpha, :id, :kind_and_make, include_blank: 
            true %>
        </div>
        <% end %>
        <div>
        <%= f.label :stars %>
        <%= f.number_field :stars, min:0, max:5 %>
    </div>
    <br>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <br>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content, size: "25x10" %>
    </div>
    <br>
    

    <%= f.submit %>

    <% end %>

app/views/reviews/show.html.erb
<h1><%= @review.guitar.make.name%> - <%= @review.guitar.kind%>: - <%= @review.title%> - <%= @review.stars%></li>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render partial: 'layouts/errors', locals: {object: @user}   %>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign Up" %>
    <% end %>

app/views/users/show.html.erb
Welcome <%= @user.username %>! You have signed in!